### ISSUE TITLE
New Validate method that considers variables

### ISSUE THREAD

**Issue by palhal** [adletec/sonic#39]
Hi. First of all: Great library.

It would be helpful if there was an `Evaluator.Validate` method overload such as:
```cs
public void Validate(string expression, IEnumerable<string> variables)
```

In addition to what the current validate method does, it would also throw a `VariableNotDefinedException` if the expression contains variables that are not part of `variables`.

I can achieve the same thing today by calling `Evaluate`, but since there is already a concept of pre-validation, I think it would be more correct to use the new proposed method instead.

**Comment by vlow** [comment]
Hi Pål! Thanks for the praise :)

First, I like the idea you propose. Allow me to add my thoughts, after trying some possible solutions in the code:

From a design perspective, _sonic_ doesn't encourage the use of pre-validation _over_ lazy-validation which will (by default) happen when evaluating. For some use-cases, throwing the exception once we're running the evaluation might actually be preferable from a performance perspective. This is especially true for checking variable completeness, since we will find this problem without any additional validation steps once we try to use a variable not present in the given dictionary.

However, the opposite can also be true. Running the complete evaluation if all we need for a certain step is to know wether an expression _can_ be evaluated is a waste of resources.

Unfortunately, it's not as checking if all variables referenced in an expression are present. An optimized AST might have folded a variable to a constant (e.g. `0*variable`) and the variable is no longer needed for evaluation.

So an acceptable implementation should:
* actually validate if an expression can be _evaluated_ using the given variables
* not evaluate the whole expression in order to answer that question

I've drafted a possible solution on a [feature branch](https://github.com/adletec/sonic/compare/feature/%2339-validate-variables). The validation of the variable completeness is performed on the AST (instead of on the `Token`-list which is used for syntax validation). This ensures that the validation behaves like `Evaluate()` would, but without the need to actually evaluation.

Unlike the syntax check performed by the basic `Validate(string expression)`-method, this code will only be used for the pre-evaluation. It is certainly faster to pre-validate without evaluating, but it's still a lot slower than simply handling the miss on the dictionary if evaluating anyway.

TL'DR: Fun challenge, thanks ;) I'll add it to the next release.

**Comment by vlow** [comment]
Pushed release to nuget. You'll find the new validation overload in version 1.4.0.

**Comment by palhal** [comment]
Wow, that was lightning fast! Thanks for the thorough answer. I can see you've been working for the last 24 hours :) 

For my use case, pre-validation is quite important. We have a service where users define their own expressions with one or more datasets. The user gives the datasets variable names of their own choosing. Possible datasets consists of electricity and water consumption, temperatures, power prices and many other things. When a user clicks the save button, the expression _and_ variables are validated before it's stored in the backend. 

A worker process is continuously evaluating the stored expressions, ranging from every second to every hour depending on the datasets included. Needless to say, it's crucial that these expressions have been validated beforehand, otherwise it would choke on countless exceptions. And since this is such a huge workload, I'm calling `EvaluatorBuilder.DisableValidation` in the hope of gaining a little performance. 

By the way, your documentation is excellent and the release notes are entertaining to read :)

**Comment by vlow** [comment]
> When a user clicks the save button, the expression and variables are validated before it's stored in the backend.
I see, makes perfect sense 👍

> And since this is such a huge workload, I'm calling EvaluatorBuilder.DisableValidation in the hope of gaining a little performance.
I'd be really interested in if and how you're noticing performance gains since migrating to _sonic_. A lot of the optimisations I've done are validated in our core application, and of course the benchmarking suite derived from it.

But since that's a sample size of 1, any real world examples are very welcome 😁.

> By the way, your documentation is excellent and the release notes are entertaining to read :)
Thank you so much :)
